### ISSUE TITLE
Confused about timestamps and lookback

### ISSUE THREAD

**Issue by MislavSag** [bagasbgy/kerasgenerator#3]
Thank you for great package!

I am a little bit confused about the deference between lookback and timestamps.

In you article: https://kerasgenerator.bagasbgy.com/articles/timeseries.html 
you said lookback defines end of the feature sequence (target - lookback) and timestamps defines beginning of the feature sequence (feature_end - timesteps + 1). But generator function in this notebook
https://github.com/jjallaire/deep-learning-with-r-notebooks/blob/master/notebooks/6.3-advanced-usage-of-recurrent-neural-networks.Rmd
has second array dimension of samples equal to looback/timestamps which would be 1 if timestamps and lookback are the same, that is sequence dimension would be equal to one?

What if I just want to to include sequence of n previous observations, are the parameters than:
lookback = 1, timestamp n?

I am also confused because in many LSTM applications I saw define only sequence_length parameter.

One more question: Generator function from above link has also delay parameter, which define how long in the future to forecast. I see you don't have that argument? It would be great to add it.

**Comment by bagasbgy** [comment]
Hi @MislavSag , sorry for a super late reply!

I just make a huge update to the package and the website. For time series articles, I also added more explanation; including some animations! Please check at https://kerasgenerator.bagasbgy.com/articles/timeseries.html.

Please inform me if you have any more confusion.

**Comment by bagasbgy** [comment]
Closing this issue due to no further question.
